const cars = [
  {
    name: "Toyoto RAV4",
    year: 2021,
    noOfPeople: 4,
    mileage: 6.1,
    fuel: "Hybrid",
    type: "Automatic",
    price: 420,
    image: "/images/download.jpeg",
  },
  {
    name: "BMW 3 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 8.2,
    fuel: "Gasoline",
    type: "Automatic",
    price: 350,
    image: "/images/BMW3Series.jpeg",
  },
  {
    name: "Volkswage T-Cross",
    year: 2020,
    noOfPeople: 4,
    mileage: 5.3,
    fuel: "Gasoline",
    type: "Automatic",
    price: 630,
    image: "/images/WolkswagenTCross.jpeg",
  },
  {
    name: "Cadillac Esclade",
    year: 2020,
    noOfPeople: 4,
    mileage: 7.7,
    fuel: "Gasoline",
    type: "Automatic",
    price: 520,
    image: "/images/CadillacEsclade.jpeg",
  },
  {
    name: "BMW 4 Seires GTI",
    year: 2021,
    noOfPeople: 4,
    mileage: 7.6,
    fuel: "Gasoline",
    type: "Automatic",
    price: 490,
    image: "/images/BMW4SeriesGTI.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
  {
    name: "BMW 4 Series",
    year: 2019,
    noOfPeople: 4,
    mileage: 7.2,
    fuel: "Gasoline",
    hybrid: "Automatic",
    price: 400,
    image: "/images/BMW4Series.jpeg",
  },
];

export default cars;
